### ISSUE TITLE
BQ Aquaris X and Andriod Firmware

### ISSUE THREAD

**Issue by Whites-ru** [adriangl/adriangl#2]
Good afternoon. I use your BQ Aquaris X smartphone and am very pleased with it. But firmware support has stopped on Android 8.1. I would like to know if it is possible to build a firmware with support for Android Treble, which would update the firmware in the future using generic system image (GSI) from Google? Respectfully, Sergey.

**Comment by adriangl** [comment]
Hello @Whites-ru!

Unfortunately I don't know if that could be done since I didn't work on FW development while I was working there, but it would be an awesome idea to give the phones longer lasting lifespans 😛. 

You can try sending an e-mail to opensource@bq.com to see if anyone could attend your request.

Best regards

**Comment by Whites-ru** [comment]
Good afternoon. Thank you for the answer, but I already wrote to the specified address and I did not get an answer. Tell me, maybe there are still addresses with whom you can contact on this issue?27 дек. 2020 г. 21:01 пользователь Adrián García <notifications@github.com> написал:

Hello @Whites-ru!

Unfortunately I don't know if that could be done since I didn't work on FW development while I was working there, but it would be an awesome idea to give the phones longer lasting lifespans 😛.

You can try sending an e-mail to opensource@bq.com to see if anyone could attend your request.

Best regards

**Comment by adriangl** [comment]
Hi @Whites-ru!

I'd like to help you, but I don't know any other address you can contact to and I no longer work there, so I can't offer any more options to reach them, unfortunately.

Sorry I can't be of more help.
