### ISSUE TITLE
Pict2Cam

### ISSUE THREAD

**Issue by Alexanderkgkg** [adriangl/adriangl#5]
Hola Adrián! Estoy intentando usar tu App Pict2Cam pero me aparece un mensaje que no puedo usarla en la versión de Android que tengo. Sabes cómo puedo solucionar eso para poder usar tu App? Gracias

**Comment by adriangl** [comment]
¡Hola!
Tal y como se indica en la aplicación, Pict2Cam no funciona a partir de Android 11 por una serie de limitaciones añadidas por Google a partir de esa versión (es decir, que no puedo hacer nada al respecto).

La única opción que tienes es rootear el teléfono y seguir las instrucciones que algunos usuarios han puesto en este hilo: https://github.com/adriangl/pict2cam/issues/162.

Siento no poder ayudarte más, pero espero que puedas solucionarlo con lo que comento ;)
